name: Publish Docker image
on:
  push:
    tags:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Copy repo files
        uses: actions/checkout@master

      - name: Publish image to GitHub Package Registry
        uses: matootie/github-docker@v1.0.1
        with:
          username: usernam3
          personalAccessToken: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
