name: Publish Docker image
on:
  push:
    tags:
      - '*'
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:

      - name: Copy repo files
        uses: actions/checkout@v2

      - name: Set env
        run: echo ::set-env name=RELEASE_VERSION::$(echo ${GITHUB_REF:10})

      - name: Publish image to GitHub Container Registry
        run: |
          echo ${{ secrets.PERSONAL_ACCESS_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
          docker pull ghcr.io/${{github.repository}}
          docker build -t ghcr.io/${{github.repository}}:${{ env.RELEASE_VERSION }} -t ghcr.io/${{github.repository}}:latest . --cache-from ghcr.io/${{github.repository}}
          docker push ghcr.io/${{github.repository}}
